### ISSUE TITLE
compile x64 - ppather System.BadImageFormatException

### ISSUE THREAD

**Issue by alejo9010** [Xian55/WowClassicGrindBot#118]
Hi man, sorry to bother again
i managed to move almost everything to winform, but im having problem with the pathing part, this is the last step to make it completely work

now i saw that it has 3 modes of creating a pathing, remotev1, remotev2, and local, so im triying to use local, the bot its selecting the right pathing method and all that

but one 'try' is getting triggered in GoapPerformGoal(), when it tries to await newGoal.PerformAction();, it goes to the catch when the goal is " Follow Route Goal" or "Sell", and these are the exceptions:
Exception thrown: 'System.BadImageFormatException' in PathingAPI.dll
Exception thrown: 'System.BadImageFormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.BadImageFormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.BadImageFormatException' in System.Private.CoreLib.dll

the StormLib is in place, so right now im out of ideas, what you think ? 

EDIT1:

here is a longer list of the exception
`System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at StormDll.StormDll.SFileOpenArchive(String szMpqName, UInt32 dwPriority, UInt32 dwFlags, Void** phMpq)
   at StormDll.Archive.Open(String file, UInt32 Prio, UInt32 Flags) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\PPather\Triangles\StormDll.cs:line 223
   at StormDll.Archive..ctor(String file, UInt32 Prio, UInt32 Flags, Logger logger) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\PPather\Triangles\StormDll.cs:line 210
   at StormDll.ArchiveSet.AddArchive(String file) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\PPather\Triangles\StormDll.cs:line 142
   at StormDll.ArchiveSet.AddArchives(String[] files) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\PPather\Triangles\StormDll.cs:line 157
   at WowTriangles.MPQTriangleSupplier..ctor(Logger logger, DataConfig dataConfig) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\PPather\Triangles\MPQTriangleSupplier.cs:line 75
   at PathingAPI.Search.CreatePathGraph(String continent) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\Search\Search.cs:line 83
   at PathingAPI.Search..ctor(String continent, Logger logger, DataConfig dataConfig) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\Search\Search.cs:line 37
   at PathingAPI.PPatherService.Initialise(String continent) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\Search\PPatherService.cs:line 73
   at PathingAPI.PPatherService.GetWorldLocation(Int32 uiMapId, Single v1, Single v2) in C:\Users\nuvov\source\repos\Arapo\PathingAPI\Search\PPatherService.cs:line 92
   at Arapo.LocalPathingApi.FindRoute(Int32 map, WowPoint fromPoint, WowPoint toPoint) in C:\Users\nuvov\source\repos\Arapo\Arapo\PathingApi\LocalPathingApi.cs:line 63
   at Core.Goals.FollowRouteGoal.RefillRouteToNextWaypoint(Boolean forceUsePathing) in C:\Users\nuvov\source\repos\Arapo\Core\Goals\FollowRouteGoal.cs:line 350
   at Core.Goals.FollowRouteGoal.PerformAction() in C:\Users\nuvov\source\repos\Arapo\Core\Goals\FollowRouteGoal.cs:line 150
   at Core.Goals.GoalThread.GoapPerformGoal() in C:\Users\nuvov\source\repos\Arapo\Core\Goals\GoalThread.cs:line 63`

**Comment by Xian55** [comment]
Hey you have to build x86 version since the storm lib dll is x86.

In order to build x64 have to recompile the storm lib dll by yourself.

You can avoid all of this if you run the pathing out of process.

https://github.com/Xian55/WowClassicGrindBot#running-on-its-own-server

**Comment by alejo9010** [comment]
ok, chnage the platform to x86, now it extract from common-2.MPQ but still it wont navigate, heres my debugger
https://pastebin.com/11gCsLtn

**Comment by Xian55** [comment]
Are you sure about `PathingAPI\MPQ\ccode.dll` and `PathingAPI\MPQ\ccode.dll` is copied to the output(bin) folder respectively?

**Comment by alejo9010** [comment]
yes, u were right ccode were missing
but still, got some errors too, here https://pastebin.com/CycagpNn 
i think most of my problem are from missing libraries =/

**Comment by Xian55** [comment]
if you referring to `Exception thrown: 'System.IO.EndOfStreamException' in System.Private.CoreLib.dll` errors these are fine do not bother with those.

However not seeing any issue, beside it seems the app just exits after `Build hash  92374` ?

**Comment by alejo9010** [comment]
when i try to start the pathing, or when the bot, create a goal that requires pathing, then it just turn the camera to the right like a quarter, and just stand there, heres an extended debug https://pastebin.com/minWXJnL, i stopped the last one because it gets too long

**Comment by alejo9010** [comment]
nvm, theres a bug, that i have to reload the addon after i toggle the bot on, its weird, it gets stuck in SELL goal, and after i /reload then it start working.

**Comment by Xian55** [comment]
It is not a bug what you referring but a feature.
https://github.com/Xian55/WowClassicGrindBot/pull/110

**Comment by alejo9010** [comment]
> It is not a bug what you referring but a feature.
> #110
ohh i understand, the bot uses now the flush command before starting the bot

also, i want to implement now the map graph that show path and player position, but i dont know where to start, what is a good control for this purpose? also where is the logic and code for this ? i been studiying the blazor page for this, but this format is hard to understand as i have never worked with blazor before.
