### ISSUE TITLE
Stuck on follow route goal

### ISSUE THREAD

**Issue by TalkingBaboon** [Xian55/WowClassicGrindBot#223]
### Description

I'm trying to use the mage grind profile in silithus. The combat rotation and stuff works fine but the bot won't move between waypoints. I've changed the path filename to point towards the elementals in the north. See the screenshot for more info. 

I think the bot doesn't know where it is. On startup the addon is working correctly as it tells me the correct class and race, the mpq files are in the right place etc. There are no errors. 

I can't see anything in the magegrind.json file that tells the bot which zone it's in. As far as I can tell it doesn't care, it's just reads where it is and the waypoints and how to get to nearest waypoint and that's it?

I can't select all of the paths either from the drop down menu on blazor. See the screenshot it's only showing one folder and if I drag and drop some .json files into the folder it is letting me select from, then sometimes they will appear in the list and sometimes not? 

See attached screenshots for more info. 

### Addon Version

1.1.47

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

Setup the bot as normal

Edited the path in magegrind.json to target the silithus elementals

### Screenshots

![2022-01-13 08_10_04-BlazorServer — Mozilla Firefox](https://user-images.githubusercontent.com/88790664/149292037-eb19f789-a553-469c-88c5-56572ee7d3fc.png)

![2022-01-13 08_14_24-](https://user-images.githubusercontent.com/88790664/149292050-b1a1265b-cfdb-4abb-a447-2112b17e59fd.png)
![2022-01-13 08_19_58-C__WowClassicGrindBot_Json_class_MageGrind json - Notepad++](https://user-images.githubusercontent.com/88790664/149292379-01d2d2b9-0a11-4ab0-af5e-1ece7895bd24.png)

### Logs

[08:09:50:993 INF] Trying to path a new route.
[08:09:50:994 INF] Adjusted resume point
[08:09:50:994 ERR] PerformAction on FollowRouteGoal
System.ArgumentOutOfRangeException: The value needs to be either -1 (signifying an infinite timeout), 0 or a positive integer. (Parameter 'millisecondsDelay')
   at System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay)
   at Game.InputWindowsNative.KeyPressNoDelay(Int32 key, Int32 milliseconds) in C:\WowClassicGrindBot\Game\Input\InputWindowsNative.cs:line 58
   at Game.WowProcessInput.KeyPressNoDelay(ConsoleKey key, Int32 milliseconds, String description) in C:\WowClassicGrindBot\Game\Input\WowProcessInput.cs:line 114
   at Core.PlayerDirection.SetDirection(Single desiredDirection, Vector3 point, String source, Int32 ignoreDistance) in C:\WowClassicGrindBot\Core\Path\PlayerDirection.cs:line 44
   at Core.PlayerDirection.SetDirection(Single desiredDirection, Vector3 point, String source) in C:\WowClassicGrindBot\Core\Path\PlayerDirection.cs:line 32
   at Core.Goals.FollowRouteGoal.RefillRouteToNextWaypoint(Boolean forceUsePathing) in C:\WowClassicGrindBot\Core\Goals\FollowRouteGoal.cs:line 403
   at Core.Goals.FollowRouteGoal.PerformAction() in C:\WowClassicGrindBot\Core\Goals\FollowRouteGoal.cs:line 181
   at Core.Goals.GoalThread.GoapPerformGoal() in C:\WowClassicGrindBot\Core\Goals\GoalThread.cs:line 114

**Comment by Xian55** [comment]
Hello there 👋 Thanks for reaching and filling up the form.

> I can't see anything in the magegrind.json file that tells the bot which zone it's in. 

The `magegrind.json` profile uses "PathFilename": "60_Silithus_scorpid.2.json", the zone name is in the filename.

> As far as I can tell it doesn't care, it's just reads where it is and the waypoints and how to get to nearest waypoint and that's it?

The Path file only contains in-game local zone coordinates from [0-100] on both axis(x,y). I've tried to build up a structure where the parent folder name or the file name it self contains the zone name.

The `FollowRouteGoal` handles the navigation. It always assumes you are in the desired zone. Yes it attempt to find the nearest path point to the player and based on the distance, it may call the pathfinding. 

**V1** pathing can fail or time out if the distance is too high or the path is too complex. V1 is also very slow due extracting the game files on the fly and makes very precise path calculation.

**V3** pathing is way faster due its prebaked navmesh and more reliable in terms of giving back a result but the quality may not be as good as V1. Its a trade off between quality and speed.

> I can't select all of the paths either from the drop down menu on blazor. See the screenshot it's only showing one folder

The drop down component is designed such a way to handle many paths. Its a free keyword search. You have to type the file path and/or file name to shrink the results. 

>  and if I drag and drop some .json files into the folder it is letting me select from, then sometimes they will appear in the list and sometimes not?

If you add or delete any path profiles during runtime and you don't restart the BlazorServer then have to press the `Refresh` button in the path profile component in order to capture a new snapshot of the file list of `\Json\Path\`
![image](https://user-images.githubusercontent.com/367101/149330310-cebf8c6e-d8db-4380-8fa9-e735ed560575.png)

---

I've tried to answer all of your question as best as could. However I see an exception which is concerning... would like to ask to upload the log file which contains the previously mentioned exception. Whenever you experience an issue like this please upload the whole file and not just small portion of it 🙇

**Comment by TalkingBaboon** [comment]
"The drop down component is designed such a way to handle many paths. Its a free keyword search. You have to type the file path and/or file name to shrink the results." 

haha sorry :) Ok thanks for the answers, I've tried to mess around with it as much as I could to figure it out. It's quite a big project. I missed that detail where the name of the zone and the ID is in brackets next to the route, Will try above post and get back to you,

**Comment by TalkingBaboon** [comment]
Hey I increased the pixel sizes and that seems to be working a lot better however it's ignoring the loot goal now. After combat it completes the parallel goal then gets stuck for a while and then continues on with the follow path goal. I have target last target bound to G but it's not even attempting to do that.  I can't see anything else in the way the bot is setup that would make it unable to loot. I have the in-game settings, brightness, gamma etc set properly. 


In the log I just get:

[16:31:49:222 INF] Waiting for  Parallel Goal
[16:31:49:223 INF] New Plan= NO PLAN
[16:31:49:238 INF] Waiting for  Parallel Goal
[16:31:49:239 INF] New Plan= NO PLAN

for a while and then it continues with the follow path goal.

**Comment by Xian55** [comment]
As i asked before please provide the full content of the log. Based on this
```
[16:31:49:222 INF] Waiting for Parallel Goal
[16:31:49:223 INF] New Plan= NO PLAN
[16:31:49:238 INF] Waiting for Parallel Goal
[16:31:49:239 INF] New Plan= NO PLAN
```
tiny info its hard to get conclusion.

You can find all the log files next to the `\BlazorServer\out*.log`

🙇

**Comment by TalkingBaboon** [comment]
Hey sorry the latest log is here.
[out20220113_005.log](https://github.com/Xian55/WowClassicGrindBot/files/7865285/out20220113_005.log)

**Comment by Xian55** [comment]
One thing. After you start the BlazorServer and the frontend is loaded make sure to always start with pressing the `Init State` button before you load the `ClassConfiguration` file.

**Comment by Xian55** [comment]
Can you send an image from the frontend of the `Goals` component when you experience the `[INF] New Plan= NO PLAN` ?

**Comment by TalkingBaboon** [comment]
Yep, here you go. 
![2022-01-13 19_51_09-BlazorServer](https://user-images.githubusercontent.com/88790664/149399617-dd8426f2-1ea2-41db-9d5d-1ce42439389e.png)

**Comment by Xian55** [comment]
The problem seems that somehow the kill credit has been not detected by the backend.

**Comment by TalkingBaboon** [comment]
Weird it was working this morning. I don't know what I could have changed that would break it like that. I found this when I tried to build again:

"C:\WowClassicGrindbot2\PathingAPI\PPather\Triangles\ChunkedTriangleCollection.cs(20,22): warning CS0649: Field 'ChunkedTriangleCollection.UseOctree' is never assigned to, and will always have its default value false [C:\WowClassicGrindbot2\PathingAPI\PathingAPI.csproj]"

**Comment by TalkingBaboon** [comment]
No there was nothing like that to cause the bot to get stuck or anything. I built it again and no longer having the issue now although I notice on some class profiles if an extra mob is pulled during combat it won't trigger the kill credit and the loot goal will be skipped as well. It happens on mage but not on warrior?

Just wanna say I love what you are doing here is there a way we can donate?

**Comment by Xian55** [comment]
> I notice on some class profiles if an extra mob is pulled during combat it won't trigger the kill credit

Since the last rework i was yet to see such a thing. I'm very interested if you could give a repro case. 🙇 

> is there a way we can donate?

If you give a star to the project and watch that would be enough 😉

**Comment by Xian55** [comment]
Hey got any update about the issue, have you find any solutions?
