### ISSUE TITLE
screenshot easy error

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#363]
### Description

screenshot default no show.

click  toggele preview   can  show.

but run some time ,  easy  error  to exit

### Addon Version

1.5.1

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

normal setup

### Last Good Version

1.5.1

### Screenshots

<img width="969" alt="截屏2022-08-02 下午12 47 34" src="https://user-images.githubusercontent.com/5819716/182294006-12e3e4c8-f8a6-444c-bd84-1e5dbf40e874.png">

### Logs

`
Unhandled exception. System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.Image.get_Width()
   at SharedLib.NpcFinder.NpcNameFinder.PopulateLinesOfNpcNames(Bitmap bitmap) in D:\workspace\c++\WowClassicGrindBot-dev\SharedLib\NpcFinder\NpcNameFinder.cs:line 428
   at SharedLib.NpcFinder.NpcNameFinder.Update() in D:\workspace\c++\WowClassicGrindBot-dev\SharedLib\NpcFinder\NpcNameFinder.cs:line 335
   at Core.BotController.ScreenshotThread() in D:\workspace\c++\WowClassicGrindBot-dev\Core\BotController.cs:line 169
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
[11:06:41:400 INF] Unstuck by turning for 308ms
`

**Comment by Xian55** [comment]
Hello there, the preview image has been disabled for a while, since consuming a lot CPU time. I should have been removed from the Frontend long ago...

The ScreenshotThread has been changed to the point, where is no longer getting updated every `tick/cycle` so doesn't even provide live view.

**Comment by Xian55** [comment]
After #364 the exception should happen less likely.

Let me know if you encounter further issues 🙇 

Gooday

**Comment by jsRuner** [comment]
ok，I try
