### ISSUE TITLE
System.ArgumentOutOfRangeException: capacity was less than the current size

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#378]
### Description

orc  rouge, level 7,  kill first unit happen error

### Addon Version

1.6.3

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

nomal setup

### Last Good Version

1.6.3

### Screenshots

![WoWScrnShot_080522_201151](https://user-images.githubusercontent.com/5819716/183075293-8d723373-5f1d-49d4-9884-976cc5e80860.jpg)

### Logs

[20:10:38:785 INF] Kill credit detected! Known kills: 1 | Fighting with: 0
[20:10:38:791 INF] New Plan=  Consume Corpse
[20:10:38:792 INF] ----- Safe to consume a corpse.
[20:10:38:807 INF] New Plan=  Loot
[20:10:38:809 WRN] Inventory is full
[20:10:38:902 INF] [NpcNameFinder] type = Corpse
[20:10:38:930 INF] Look at possible closest corpse and try once again...
Unhandled exception. System.AggregateException: One or more errors occurred. (capacity was less than the current size. (Parameter 'value'))
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.Grow(Int32 capacity)
   at System.Collections.Generic.List`1.AddWithResize(T item)
   at SharedLib.NpcFinder.NpcNameFinder.<>c__DisplayClass140_0.<PopulateLinesOfNpcNames>g__body|0(Int32 y) in D:\soft\workspace\c++\WowClassicGrindBot-dev\SharedLib\NpcFinder\NpcNameFinder.cs:line 492
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at SharedLib.NpcFinder.NpcNameFinder.PopulateLinesOfNpcNames(Bitmap bitmap, Rectangle rect) in D:\soft\workspace\c++\WowClassicGrindBot-dev\SharedLib\NpcFinder\NpcNameFinder.cs:line 506
   at SharedLib.NpcFinder.NpcNameFinder.Update() in D:\soft\workspace\c++\WowClassicGrindBot-dev\SharedLib\NpcFinder\NpcNameFinder.cs:line 369
   at Core.BotController.ScreenshotThread() in D:\soft\workspace\c++\WowClassicGrindBot-dev\Core\BotController.cs:line 169
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()

**Comment by Xian55** [comment]
Hi, most likely you ran out of free RAM(memory). 

I suggest to do a full windows Restart, like `Start Menu -> Power -> Restart`

**Comment by jsRuner** [comment]
my RAM  is  32G, why  happen out of free RAM(memory). 
because of  path module ？

**Comment by Xian55** [comment]
In the past, seen this exception when, i was at 80-90% memory usage. That's why i suggested, to restart your pc.

Either 
* Possible memory leak
* Concurrency issue in NPCNameFinder

Have to investigate. Thanks for the report 🙇

**Comment by alex498** [comment]
I have used MemReduct to prevent such issues with memory, also i suggest to run v1 pathfinder by its own instead of using it in the bot

**Comment by coolzoom** [comment]
for hackfix xD, maybe find some c# RAM clean code to implant into the core, clean RAM while for example RAM USAGE>70%. until there is a fixed solution

**Comment by alex498** [comment]
First of all need to find where is memory leak
