### ISSUE TITLE
Error while setting up frame configuration

### ISSUE THREAD

**Issue by knepe** [Xian55/WowClassicGrindBot#398]
### Description

When trying either auto or manual frame configuration in BlazorServer, the dotnet process exits and to to get it in a working state again I need to remove the frame_config.json otherwise its just loading (no errors in output, only that it started up)

### Addon Version

1.7.13

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

* Start everything (path api, ameisenserver and blazor server)
* Setup addon, restart game, enter world
* Start frame configuration

### Logs

[22:21:56:711 INF] Found WowProcess
[22:21:56:742 INF] Client window: {X=320,Y=164,Width=1280,Height=720}
[22:21:56:772 INF] Addon installed! Version: 1.7.13
[22:21:56:777 INF] Enter configuration mode.
[22:21:57:290 INF] /nameofaddon
[22:21:58:090 INF] DataFrameMeta: hash: 10101100 | spacing: 1 | size: 1 | rows: 1 | frames: 100
[22:21:58:149 INF] Exit configuration mode.
[22:21:58:153 INF] /nameofaddon
[22:21:59:556 ERR] Unable to identify ClientVersion UnitRace and UnitClass!
[22:21:59:599 INF] Frame configuration was successful! Configuration saved!
[22:21:59:618 WRN] Addon thread stoppped!
[22:21:59:618 DBG] Frontend thread stopped!
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'areaDB' on type 'Frontend.Pages.RouteComponent'. There is no registered service of type 'Core.Dat
abase.AreaDB'.
      System.InvalidOperationException: Cannot provide a value for property 'areaDB' on type 'Frontend.Pages.RouteComponent'. There is no registered service of type 'Core.Database.A
reaDB'.
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 ne
wStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree,
 ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentExcepti
on)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'klOHOF8i-hWMhaq62CFyk5yqwAOQNrmBqaGC24szye0'.
      System.InvalidOperationException: Cannot provide a value for property 'areaDB' on type 'Frontend.Pages.RouteComponent'. There is no registered service of type 'Core.Database.A
reaDB'.
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 ne
wStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree,
 ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentExcepti
on)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by Xian55** [comment]
Hello there,  👋 thanks for pointing out the issue 🙇 !

The mentioned exception are actually known and it is happening most likely because using the `Index` page for both configuration and dashboard view. So after restart don't need to change url path to see the relevant state.

After the restart happened, for a brief moment its going to use the Configuration based Dependency Injection state where the `areaDB` has no implementation. 

```css
Unhandled exception rendering component: Cannot provide a value for property 'areaDB' on type 'Frontend.Pages.RouteComponent'. There is no registered service of type 'Core.Dat
abase.AreaDB'.
System.InvalidOperationException: Cannot provide a value for property 'areaDB' on type 'Frontend.Pages.RouteComponent'. There is no registered service of type 'Core.Database.A
reaDB'.
```

It should cause no issue since the service is going down anyway. Not nice but it worked 😅 

I might do a separate configuration page, and after the restart - with valid configs exists - might just redirect to dashboard instead.

---

The scary part what you shared is that, its unable to validate the frame cells integrity and yet still let you thru, on top of that saves its invalid configuration to disk 😨  
```css
[22:21:59:556 ERR] Unable to identify ClientVersion UnitRace and UnitClass!
[22:21:59:599 INF] Frame configuration was successful! Configuration saved!
```

**Comment by knepe** [comment]
Thanks for the super quick fix! 👍 I will test it when I get back from work. 

Is the root issue, that it cant validate the ClientVersion, UnitRace and UnitClass, a known issue on TBC Classic client? 
Or is it just me? 
I tried to debug it but I couldn't make anything useful out of it, cause I don't really know how the data works/should look like

**Comment by Xian55** [comment]
> Is the root issue, that it cant validate the ClientVersion, UnitRace and UnitClass, a known issue on TBC Classic client?
Or is it just me?

yes, exactly. It seems the data cells not correct. I have a few guesses:
* unable to exit Configuration mode, maybe simply the input commands where not received by the game (Copy & Paste)
* there could be rounding errors thus the cells not ending up where they supposed to be. In that case i would recommend to try to change the [cell size](https://github.com/Xian55/WowClassicGrindBot/wiki/Guidance-for-good-DataFrame)

**Comment by knepe** [comment]
Ah okay. 
I actually saw the copy & paste commands in the chat window, so I dont think that is the issue.
I'm gonna try increase the cell size, and also make sure to follow that guide, especially the thing with the background in top left corner.
I missed reading that guide and I think I was standing outside of UC just looking at the direction of the zeppelin building, so I guess there might have been quite alot of different colors at the top left corner :D

**Comment by Xian55** [comment]
> I missed reading that guide and I think I was standing outside of UC just looking at the direction of the zeppelin building, so I guess there might have been quite alot of different colors at the top left corner :D

In theory only the Tooltip and loading screen could be rendered above the dataframes. im looking forward your finding.

**Comment by knepe** [comment]
Update: Your fixed worked, it does not save invalid frame config now. 
As for the root issue, the thing that worked was changing cell size to 2. Thanks! Will close

**Comment by Xian55** [comment]
Hello there, i have a few question regarding your setup.

Can you tell the followings about your setup
* Windows ->  Desktop resolution size
* Windows -> Display Settings -> Scale and layout -> Percentage
* Game -> System -> Graphics -> Windowed mode
* Game -> System -> Graphics -> Window Size
* Game -> System -> Graphics -> Render Scale
* Game -> System  -> Advanced -> If enabled, UI Scale percentage

Finally in game can you type the following and let me know the results:
```
/dump GetCVar("UiScale")
```

🙇

**Comment by knepe** [comment]
> * Windows ->  Desktop resolution size
> * Windows -> Display Settings -> Scale and layout -> Percentage
> * Game -> System -> Graphics -> Windowed mode
> * Game -> System -> Graphics -> Window Size
> * Game -> System -> Graphics -> Render Scale
> * Game -> System  -> Advanced -> If enabled, UI Scale percentage

Windows -> Desktop resolution size **1920x1080**
Windows -> Display Settings -> Scale and layout -> Percentage **125%**
Game -> System -> Graphics -> Windowed mode **true**
Game -> System -> Graphics -> Window Size **1280x720**
Game -> System -> Graphics -> Render Scale **100%**
Game -> System -> Advanced -> If enabled, UI Scale percentage **not enabled, 1.0**

/dump GetCVar("UiScale") returns "1.0" in game

**Comment by knepe** [comment]
Btw, do you have any IM(discord?) or something I can talk to you? The bot code looks great, but I have issues recording a new path (and some other stuff). I got 13+ c# experience through work so I might be able to help out with issues. My discord handle is knepe#8100 if you want to add
