### ISSUE TITLE
Known Issue: Crash upon UAC elevation prompt

### ISSUE THREAD

**Issue by AsterNighT** [Xian55/WowClassicGrindBot#405]
### Description

While the bot is running, if a UAC elevation is invoked (thus call up the prompts asking you whether to grant it or not), the bot would crash. 

### Addon Version

1.7.16

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

1. Start the bot
2. Run something as Administrator (windows terminal with elevated privileges will do)
3. See it crash

### Last Good Version

Nope

### Screenshots

I cannot really screen shot the UAC prompt

### Logs

```
Unhandled exception. System.ComponentModel.Win32Exception (6): 句柄无效。
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at System.Drawing.Graphics.CopyFromScreen(Point upperLeftSource, Point upperLeftDestination, Size blockRegionSize)
   at Core.AddonDataProviderGDI.Update() in F:\work\personal\WowClassicGrindBot\Core\Addon\AddonDataProviderGDI.cs:line 75
   at Core.AddonReader.Update() in F:\work\personal\WowClassicGrindBot\Core\Addon\AddonReader.cs:line 117
   at Core.BotController.AddonThread() in F:\work\personal\WowClassicGrindBot\Core\BotController.cs:line 157
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
```
The Chinese means `Invalid Handle`

**Comment by Xian55** [comment]
Hello there, 👀 

I know about such an error, both `GDI` and `DXGI` side. 

So since the app is a pixel bot, it requires to see the game client window all time to operate. 

Not sure about how to mitigate the issue. Feel free to contribute to this matter.

**Comment by AsterNighT** [comment]
Indeed, but a few seconds without data should not kill it.
Windows seems to club its users if it is a secure prompt they're trying to taking a shot of. The first approach comes to my mind is to simply catch the `Invalid handle` error. But I'm not sure if there are anything else that triggers this error.

**Comment by Xian55** [comment]
`Invalid handle` Error could happen for many reasons, simply catching the error doesn't mean it could recover from that state. In the past there was an issue with dotnet core version similar error has happened before #154. Out side of the scope of the project capabilities.

On the other hand this only solves the issue of `GDI` based provider.

`DXGI` based provider unable to recover as the `DeviceContext` is disconnected, which means have to reinitialize the chain of objects, Adapter, Output, DesktopDuplication, Texture the whole object. 

On the other hand, if the UAC prompt happens when the user is not nearby to take action. 

For me sounds like a very rare issue. I'm opting in to just record as Known issue.
