### ISSUE TITLE
Unhandled exception "System.ArgumentOutOfRangeException" NpcNameTargeting.AquireNonBlacklisted

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#415]
### Description

This one is hard for me to troubleshoot. Happening on Two different computers one being my main Gaming rig that has lots of resources. It seems to happen at random times. Sometimes it will run for a couple of hours. Sometimes like today it will run for like 10 min.

Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Core.Goals.NpcNameTargeting.AquireNonBlacklisted(CancellationToken ct) in C:\Users\Adam-Laptop1\Desktop\adam1\YumYum4\Core\GoalsComponent\NpcNameTargeting.cs:line 136
   at Core.Goals.TargetFinder.LookForTarget(NpcNames target, CancellationToken ct) in C:\Users\Adam-Laptop1\Desktop\adam1\YumYum4\Core\GoalsComponent\TargetFinder.cs:line 35
   at Core.Goals.FollowRouteGoal.Thread_LookingForTarget() in C:\Users\Adam-Laptop1\Desktop\adam1\YumYum4\Core\Goals\FollowRouteGoal.cs:line 225
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

C:\Users\Adam-Laptop1\Desktop\adam1\YumYum4\BlazorServer>pause

### Addon Version

1.7.17

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

Nothing special is going on the bot just stops. With the error message in the description.

### Logs

[out20220901.log](https://github.com/Xian55/WowClassicGrindBot/files/9471896/out20220901.log)

**Comment by adamssullivan** [comment]
[Warlock_WOTLK.txt](https://github.com/Xian55/WowClassicGrindBot/files/9472383/Warlock_WOTLK.txt)
This is my class

**Comment by Xian55** [comment]
Thanks for the info, Class Config is fine, doing investigation bit later, busy atm.

**Comment by adamssullivan** [comment]
Sounds good. Thanks for any help in the future.

**Comment by adamssullivan** [comment]
I was able to use "attendedgrind" mode for about 1 hr and have not seen any issues. After about 10 min on "Grind" mode, it fails in the same way

**Comment by Xian55** [comment]
With https://github.com/Xian55/WowClassicGrindBot/pull/419 fix merged to `dev`, the issue should no longer appear. 🤞 

Let me know if you encounter this kind of issue.

**Comment by adamssullivan** [comment]
I will try it right now and report back

**Comment by adamssullivan** [comment]
No issues yet for about 30 min. Thanks!
