### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Cucoldun** [Xian55/WowClassicGrindBot#438]
### Description

Hello there.
When running the bot via blazor server, an error occurs and it reboots showing update 1 of 8 and so on. However, nothing happens when the update completes.

### Addon Version

1.2.3

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

all steps for downloading and activating the bot from the guide

### Logs

[19:59:48:484 DBG] RemoteV3 not available!
[19:59:48:485 INF] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[19:59:48:493 DBG] LocalPathingApi: Hooray, MPQ files exist.
[19:59:48:495 INF] Using Local(LocalPathingApi) pathing API.
[19:59:48:496 INF] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[19:59:48:842 DBG] Woohoo, I have read the player class. You are a NightElf Druid.
[19:59:48:846 INF] [NpcNameFinder] searchMode = Simple
[19:59:51:699 INF] /titleflush
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Core.ActionBarCostReader.Read(IAddonDataProvider reader) in C:\WowClassicGrindBot\Core\Actionbar\ActionBarCostReader.cs:line 61
   at Core.AddonReader.Update() in C:\WowClassicGrindBot\Core\Addon\AddonReader.cs:line 117
   at Core.BotController.AddonThread() in C:\WowClassicGrindBot\Core\BotController.cs:line 157
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()

C:\WowClassicGrindBot\BlazorServer>pause

**Comment by Xian55** [comment]
Hello there.

There supposed to be a file `C:\WowClassicGrindBot\BlazorServer\frame_config.json` could you upload that file, if exists?

Please upload the logfiles, logfiles can be found here:

- `WowClassicGrindBot\BlazorServer\`
- `WowClassicGrindBot\BlazorServer\bin\Release\net6.0`
- `WowClassicGrindBot\BlazorServer\bin\x64\Release\net6.0`
- `WowClassicGrindBot\BlazorServer\bin\x86\Release\net6.0`

example file format: `out20221004.log`

---

Be sure to have write access to `C:\WowClassicGrindBot\` folder and its children. I would not advise to start BlazorServer as administrator.

**Comment by Cucoldun** [comment]
[frame_config.zip](https://github.com/Xian55/WowClassicGrindBot/files/9747922/frame_config.zip)
2022-10-10 20:28:51.161 +03:00 [INF] Startup()
2022-10-10 20:28:51.615 +03:00 [INF] Using AddonDataProviderGDI
2022-10-10 20:28:54.637 +03:00 [ERR] RemotePathingAPIV3: The connection has not been established because the destination computer rejected the connection request. 127.0.0.1:47111
2022-10-10 20:28:58.772 +03:00 [ERR] RemotePathingAPI: PingServer - Connected: false - http://localhost:5001/api/PPather/ Gave(The connection was not established because the destination computer rejected the connection request. (localhost:5001))
2022-10-10 20:28:58.775 +03:00 [INF] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2022-10-10 20:28:58.776 +03:00 [DBG] RemoteV3 not available!
2022-10-10 20:28:58.777 +03:00 [INF] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2022-10-10 20:28:58.828 +03:00 [DBG] LocalPathingApi: Hooray, MPQ files exist.
2022-10-10 20:28:58.830 +03:00 [INF] Using Local(LocalPathingApi) pathing API.
2022-10-10 20:28:58.831 +03:00 [INF] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2022-10-10 20:28:59.605 +03:00 [DBG] Woohoo, I have read the player class. You are a NightElf Druid.
2022-10-10 20:28:59.609 +03:00 [INF] [NpcNameFinder] searchMode = Simple
2022-10-10 20:29:02.087 +03:00 [INF] /titleflush

**Comment by Cucoldun** [comment]
[frame_config.zip](https://github.com/Xian55/WowClassicGrindBot/files/9747942/frame_config.zip)
[out20221010.log](https://github.com/Xian55/WowClassicGrindBot/files/9747943/out20221010.log)

**Comment by Xian55** [comment]
Seems everything fine here, as of this moment can't tell what's happened.

If you could give more info about your setup would be helpful.

* monitor resolution
* game resolution
* windowed mode
* windows GUI scale
* game fps

---

Be sure that the, game client top left corner is visible on your screen all time, no other application covers the area.

**Comment by Cucoldun** [comment]
Anti-aliasing was activated in the settings, the settings went wrong. Thanks for your help!
