### ISSUE TITLE
Chat/ChatReader arg out of range exception

### ISSUE THREAD

**Issue by jacobhamblin** [Xian55/WowClassicGrindBot#567]
### Description

Expectation: bot does its thing as configured
What happened: lost connection to localhost:5000, prompts to reload

Was just running a simple rotation on some mobs in the barrens

```
[04:29:39:125 I] [GoapAgent      ] New Plan=  Follow Route
[04:29:39:127 I] [Navigation     ] [LocalPathingApi] distance is close 17.654783. Keep RouteToWaypoint.
[04:29:40:371 I] [NpcNameFinder] type = None | mode = Fuzzy
[04:29:41:555 E] Specified argument was out of the range of valid values. (Parameter 'start')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at Core.ChatReader.Update(IAddonDataProvider reader) in C:\Users\jacob\Downloads\WowClassicGrindBot-devv\WowClassicGrindBot-dev\Core\Chat\ChatReader.cs:line 43
   at Core.AddonReader.Update() in C:\Users\jacob\Downloads\WowClassicGrindBot-devv\WowClassicGrindBot-dev\Core\Addon\AddonReader.cs:line 73
   at Core.BotController.AddonThread() in C:\Users\jacob\Downloads\WowClassicGrindBot-devv\WowClassicGrindBot-dev\Core\BotController.cs:line 152
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at Core.ChatReader.Update(IAddonDataProvider reader) in C:\Users\jacob\Downloads\WowClassicGrindBot-devv\WowClassicGrindBot-dev\Core\Chat\ChatReader.cs:line 43
   at Core.AddonReader.Update() in C:\Users\jacob\Downloads\WowClassicGrindBot-devv\WowClassicGrindBot-dev\Core\Addon\AddonReader.cs:line 73
   at Core.BotController.AddonThread() in C:\Users\jacob\Downloads\WowClassicGrindBot-devv\WowClassicGrindBot-dev\Core\BotController.cs:line 152
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Addon Version

1,7,52

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

Don't think it was related to anything I was doing. Could be wrong

### Logs

[out20240202_001.log](https://github.com/Xian55/WowClassicGrindBot/files/14145760/out20240202_001.log)

**Comment by Xian55** [comment]
Hello there,

I just did a quick test to check the [ChatReader](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/Chat/ChatReader.cs#L41) component integrity, it seems working fine.

I have an assumption about that your `FrameConfig.json` might be invalid thus the backend is unable to read the correct values. As I'm seeing many **negative milliseconds(ms)** values in the logs, which means the the designed await times are timed out. In other words it does not work as intended.
example from the logs:
```py
[03:40:41:551 I] [GoapAgent      ] New Plan=  Combat
[03:40:44:047 I] [Haunt          ] instant usable: True->False | current: False->False | CAST_SUCCESS->CAST_SUCCESS
[03:40:45:345 I] [Haunt          ] instant input 63ms SPELL_FAILED_NOT_READY -1233.5497ms
[03:40:46:587 I] [Curse of Agony ] instant input 59ms CAST_SUCCESS -1181.5092ms
[03:40:47:851 I] [Curse of Agony ] instant usable: False->False | current: False->False | CAST_SUCCESS->CAST_SUCCESS
[03:40:50:365 I] [Shoot          ] instant usable: True->False | current: False->True | CAST_SUCCESS->CAST_SUCCESS
[03:40:51:631 I] [Shoot          ] instant input 89ms CAST_SUCCESS -1174.0035ms
[03:40:53:780 I] [GoapAgent      ] Kill credit detected! Known kills: 1 | Fighting with: 0
[03:40:54:095 I] [Shoot          ] instant usable: True->False | current: False->False | CAST_SUCCESS->CAST_SUCCESS
[03:40:55:331 I] [Shoot          ] instant input 61ms SPELL_FAILED_NOT_READY -1172.261ms
[03:40:55:332 I] [CombatGoal     ] Lost target!
```

I recommend to delete the `FrameConfig.json` next to the executable and run the BlazorServer to regenerate the config file again. Also after successfully creating the `FrameConfig.json` file be sure to do a quick [validation](https://github.com/Xian55/WowClassicGrindBot/wiki/Validating-FrameConfiguration) to check everything's in order.

You can trigger this exception again by sending a say message or whispering yourself.

If the issue still persist i may recommend the followings:
* Be sure that the glow effect is turned off. Type this in-game chat `/console ffxGlow 0`
* Disable all addons beside **your addon** and **bindpad**, other addons might interfere
* Be sure that the graphics settings such as gamma and colors are set to default
* Be sure that no ui upscale is happening (Options -> **Use UI Scale**)
* Be sure that no upscaling is applied in game(Options -> **Render Scale**) or externally by graphics driver
* Try to run the game Full screen mode

You may have to do the `FrameConfig.json` delete and recreation multiple times.

**Comment by jacobhamblin** [comment]
Will test, thanks

**Comment by Xian55** [comment]
* Did you had time to try out the suggested changes ?
* Have you noticed the issue reoccurring since ?

Gooday!

**Comment by Xian55** [comment]
Should be mitigate by #640
