### ISSUE TITLE
After creating the frame configuration, Blazor Server reports an exception when you select yourself as the target in the game.

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#606]
### Description

When I clicked auto->start on the Frame Configuration page, my next action was to select myself as the target in the game, and Blazor Server reported the following error

[22:09:26:188 E] [RemoteNavigationManager] Navigation failed when changing the location to /
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
[22:09:26:201 E] [CircuitHost    ] Unhandled exception in circuit 'OczKXA4X9LG5O356_fUFWAChWrDk_fiGjSIFUC-IQm0'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()

### Addon Version

1.7.57

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

step1: frame configuration->auto->start
step2:Choose yourself as the target(in game)

### Screenshots

no

### Logs

BlazorServer was restarted by me many times, so there are multiple different log files.

[out20240708_004.log](https://github.com/user-attachments/files/16130729/out20240708_004.log)
[out20240708_005.log](https://github.com/user-attachments/files/16130730/out20240708_005.log)
[out20240708_006.log](https://github.com/user-attachments/files/16130732/out20240708_006.log)
[out20240708_007.log](https://github.com/user-attachments/files/16130733/out20240708_007.log)
[out20240708_008.log](https://github.com/user-attachments/files/16130734/out20240708_008.log)

**Comment by Xian55** [comment]
Hello that's expected behaviour, as the Configration mode and Normal mode are separated it is by design. During normal mode it is not allowed to resize rescale the wow client as the cell size spacing might be changed and might be incorrect due rounding errors.

**Comment by cppbeliever** [comment]
@Xian55 
thanks!
