### ISSUE TITLE
[NpcNameFinder] Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#609]
### Description

HeadLessServer reports an error after selling an item to a merchant.Is it related to running out of food and drink?

### Addon Version

1.7.57

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

HeadLessServer reports an error after selling an item to a merchant

### Screenshots
![aaa](https://github.com/user-attachments/assets/fe8bf8e4-030f-4c44-86a3-d60f9ee6c706)

### Logs

[headless_out20240713.log](https://github.com/user-attachments/files/16200696/headless_out20240713.log)
[out20240713.log](https://github.com/user-attachments/files/16200697/out20240713.log)

**Comment by Xian55** [comment]
Hello, looking into it

```log
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.) (Specified argument was out of the range of valid values.) (Specified argument was out of the range of valid values.)
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---

   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---

   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at SixLabors.ImageSharp.Advanced.ParallelRowIterator.IterateRows[T,TBuffer](Rectangle rectangle, ParallelExecutionSettings& parallelSettings, T& operation)
   at SharedLib.NpcFinder.NpcNameFinder.Update() in D:\HuB\WowClassicGrindBot-dev\WowClassicGrindBot-dev\SharedLib\NpcFinder\NpcNameFinder.cs:line 337
   at Core.BotController.ScreenshotThread() in D:\HuB\WowClassicGrindBot-dev\WowClassicGrindBot-dev\Core\BotController.cs:line 197
 ---> (Inner Exception #1) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---

   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

it seems 
```
at SharedLib.NpcFinder.NpcNameFinder.Update() in D:\HuB\WowClassicGrindBot-dev\WowClassicGrindBot-dev\SharedLib\NpcFinder\NpcNameFinder.cs:line 337
```
went out of bound.

Seems like a weird issue, not sure how to tackle it or even reproduce it.

**Comment by cppbeliever** [comment]
@Xian55  thanks for your response

**Comment by Xian55** [comment]
No need to close this one. Let it open, so i wont forget about it.

**Comment by Xian55** [comment]
It occurred again 

```
[22:38:57:110 E] One or more errors occurred. (Specified argument was out of the range of valid values.)
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.)
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at SixLabors.ImageSharp.Advanced.ParallelRowIterator.IterateRows[T,TBuffer](Rectangle rectangle, ParallelExecutionSettings& parallelSettings, T& operation)
   at SharedLib.NpcFinder.NpcNameFinder.Update() in X:\A\WowClassicGrindBot\SharedLib\NpcFinder\NpcNameFinder.cs:line 337
   at Core.BotController.ScreenshotThread() in X:\A\WowClassicGrindBot\Core\BotController.cs:line 197Unhandled exception. System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.)
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at SixLabors.ImageSharp.Advanced.ParallelRowIterator.IterateRows[T,TBuffer](Rectangle rectangle, ParallelExecutionSettings& parallelSettings, T& operation)
   at SharedLib.NpcFinder.NpcNameFinder.Update() in X:\A\WowClassicGrindBot\SharedLib\NpcFinder\NpcNameFinder.cs:line 337
   at Core.BotController.ScreenshotThread() in X:\A\WowClassicGrindBot\Core\BotController.cs:line 197
X:\A\WowClassicGrindBot\HeadlessServer\bin\Release\net9.0\HeadlessServer.exe (process 9908) exited with code -532462766 (0xe0434352).
```

**Comment by Xian55** [comment]
Should be fixed after #660
