### ISSUE TITLE
CancelationToken has already been disposed

### ISSUE THREAD

**Issue by lionaneesh** [Xian55/WowClassicGrindBot#643]
### Description

Hello, in CastingHandler.cs there is cancelation token which can sometimes crash the bot. I think we should check if the token has been disposed or try catch that. 

### Addon Version

Latest

### World of Warcraft Client

World of Warcraft Classic

### Reproduction Steps

Its hard to reproduce it. 

### Last Good Version

No

**Comment by Xian55** [comment]
Please provide logs to look at it.

Do not alter the log just upload the raw file.

And the used ClassProfile as well!

Thanks

**Comment by Xian55** [comment]
Recently i've added a new feature #649 which more extensively uses the `CancellationToken`.

After conducting extensive testing i was failed to reproduce the the mentioned issue.

I've primarily tested `KeyAction.Interrupt` feature with
* [Shaman_60_elemental_interrupt.json](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Json/class/Shaman_60_elemental_interrupt.json)
* [Mage_6.json](https://github.com/user-attachments/files/18268639/Mage_6.json)

Also here's a test one with a low level(6-8lvl) mage profile which primarily uses `Fireball`. The Fireball DoT can trigger the `Fire Blast` conditions at various time window of the in progress cast.

```json
{
  "ClassName": "Mage",
  "Loot": true,
  "PathFilename": "5_Gnome.json",
  "PathThereAndBack": true,
  "PathReduceSteps": false,
  "IntVariables": {
    "Item_Conjure_Drink": 5350,
    "Item_Conjure_Food": 5349,
    "MIN_FOOD%": 50,
    "MIN_WATER%": 50,
    "MIN_MANA_SPELL%": 10
  },
  "Pull": {
    "Sequence": [
      {
        "Name": "Frostbolt",
        "Key": "1",
        "HasCastBar": true,
        "Requirements": [
          "SpellInRange:3",
          "Mana% > MIN_MANA_SPELL%"
        ]
      },
      {
        "Name": "Shoot",
        "Key": "0",
        "Item": true,
        "Requirements": [
          "HasRangedWeapon",
          "!Shooting",
          "SpellInRange:1",
          "Mana% < MIN_MANA_SPELL%"
        ]
      },
      {
        "Name": "Approach",
        "Requirements": [
          "!Casting",
          "!Shooting"
        ]
      }
    ]
  },
  "Flee": {
    "Sequence": [
      {
        "Name": "Flee",
        "Requirement": "(MobCount > 1 && Health% < 60) || TargetElite" 
      }
    ]
  },
  "Combat": {
    "Sequence": [
      {
        "Name": "Fire Blast",
        "Key": "5",
        "Requirements": [
          "TargetAlive && TargetHealth% < 35",
          "SpellInRange:4"
        ]
      },
      {
        "Name": "Fireball",
        "Key": "2",
        "HasCastBar": true,
        "AfterCastWaitCastbar": true,
        "Requirements": [
          "Mana% > MIN_MANA_SPELL%",
          "TargetHealth% > 35"
        ],
        "Interrupt": "CanRun:Fire Blast",
        "CancelOnInterrupt": true
      },
      {
        "Name": "Shoot",
        "Key": "0",
        "Item": true,
        "Requirements": [
          "HasRangedWeapon",
          "!Shooting",
          "SpellInRange:1"
        ]
      },
      {
        "Name": "AutoAttack",
        "Requirements": [
          "!HasRangedWeapon",
          "!AutoAttacking"
        ]
      },
      {
        "Name": "Approach",
        "Requirements": [
          "!Casting",
          "AutoAttacking"
        ]
      }
    ]
  },
  "Parallel": {
    "Sequence": [
      {
        "Name": "Food",
        "Key": "=",
        "Requirement": "Health% < MIN_FOOD%"
      },
      {
        "Name": "Drink",
        "Key": "-",
        "Requirement": "Mana% < MIN_WATER%"
      }
    ]
  },
  "Adhoc": {
    "Sequence": [
      {
        "Name": "Frost Armor",
        "Key": "3",
        "Requirement": "!Frost Armor"
      },
      {
        "Name": "Arcane Intellect",
        "Key": "4",
        "Requirement": "!Arcane Intellect",
        "Log": false
      },
      {
        "Name": "Conjure Drink",
        "Key": "9",
        "HasCastBar": true,
        "Requirement": "!BagItem:Item_Conjure_Drink:4",
        "AfterCastWaitCastbar": true,
        "AfterCastWaitBag": true
      },
      {
        "Name": "Conjure Food",
        "Key": "8",
        "HasCastBar": true,
        "Requirement": "!BagItem:Item_Conjure_Food:4",
        "AfterCastWaitCastbar": true,
        "AfterCastWaitBag": true
      }
    ]
  },
  "NPC": {
    "Sequence": [
      {
        "Cost": 6,
        "Name": "Repair",
        "Key": "C",
        "Requirement": "Durability% < 35",
        "PathFilename": "5_Gnome_Vendor.json"
      },
      {
        "Cost": 6,
        "Name": "Sell",
        "Key": "C",
        "Requirements": [
          "BagFull",
          "BagGreyItem"
        ],
        "PathFilename": "5_Gnome_Vendor.json"
      }
    ]
  }
}
```

**Comment by Xian55** [comment]
Today i had a chance to reproduce the issue, not sure about the perquisites tho. Probably related my mistake https://github.com/Xian55/WowClassicGrindBot/commit/fe54f1faf15a91cb32b447d35822dcbdb251ddff

```log
[23:34:17:582 I] [NpcNameFinder] type = None | mode = Fuzzy
[23:34:17:583 I] [GoapAgent        ] New Plan=  Approach Target
[23:34:17:614 I] [NpcNameTargeting ] NPC found: Kill | 0 | Rectangle [ X=730, Y=97, Width=22, Height=2 ]
[23:34:17:614 I] [FollowRouteGoal  ] Found target!
[23:34:17:994 D] [ApproachTargetGoal] Too far (45 yard), start moving forward!
[23:34:20:530 I] [GoapAgent        ] New Plan=  Pull Target
[23:34:20:594 I] [MountHandler     ] Mounted ? True
[23:34:20:594 I] [PullTargetGoal   ] Stop auto interact!
[23:34:21:114 I] [CastingHandler   ] [Hunter's Mark    ] castbar input 54ms 179.1702ms
[23:34:24:833 I] [GoapAgent        ] New Plan=  Combat
[23:34:24:848 I] [CombatTracker    ] Entered Combat
[23:34:25:284 I] [CastingHandler   ] [Auto Shot        ] castbar input 40ms 211.9548ms
[23:34:25:950 I] [BagChangeTracker ] 43 -> 42 Ice Threaded Arrow
[23:34:26:115 I] [BagChangeTracker ] 42 -> 41 Ice Threaded Arrow
[23:34:26:131 I] [CastingHandler   ] [Serpent Sting    ] castbar input 69ms 176.1697ms
[23:34:28:685 I] [BagChangeTracker ] 41 -> 40 Ice Threaded Arrow
[23:34:29:133 I] [BagChangeTracker ] 40 -> 39 Ice Threaded Arrow
[23:34:29:133 I] [CastingHandler   ] [Arcane Shot      ] castbar input 40ms 222.665ms
[23:34:32:004 I] [BagChangeTracker ] 39 -> 38 Ice Threaded Arrow
[23:34:34:839 I] [BagChangeTracker ] 38 -> 37 Ice Threaded Arrow
[23:34:35:339 I] [GoapAgent        ] Kill credit detected! Session Total: 7 | Last Combat: 1 | Currently fighting: 0
[23:34:35:340 W] [CastingHandler   ] [Arcane Shot      ] ... Failed try again!
[23:34:35:359 E] The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Core.Wait.Update(CancellationToken token) in X:\WowClassicGrindBot\Core\GoalsComponent\Wait.cs:line 29
   at Core.Goals.CastingHandler.CastCastbar(KeyAction item, CancellationToken token) in X:\WowClassicGrindBot\Core\GoalsComponent\CastingHandler.cs:line 287
   at Core.Goals.CastingHandler.Cast(KeyAction item, Func`1 interrupt) in X:\WowClassicGrindBot\Core\GoalsComponent\CastingHandler.cs:line 689
   at Core.Goals.CombatGoal.Update() in X:\WowClassicGrindBot\Core\Goals\CombatGoal.cs:line 108
   at Core.GOAP.GoapAgent.GoapThread() in X:\WowClassicGrindBot\Core\GOAP\GoapAgent.cs:line 219
```

After 3f5b0adf51a2322fd7bf9a8b95df331ca4708233 the situation should be better as the [Wait.Update](https://github.com/Xian55/WowClassicGrindBot/blob/741c6be36b6892a15b5d79f6b6bfe9203e2f083d/Core/GoalsComponent/Wait.cs#L33) knows about [OperationCanceledException](https://learn.microsoft.com/en-us/dotnet/api/system.operationcanceledexception?view=net-9.0)
